import logging
from datetime import datetime, timezone

from flask import Blueprint, jsonify, request, render_template

from app.controllers.analysis_controller import analysis_controller
from app.models.model_loader import model_loader

logger = logging.getLogger(__name__)

api_bp = Blueprint("api", __name__)
main_bp = Blueprint("main", __name__)


# ─── UI Routes ────────────────────────────────────────────────────────────────

@main_bp.route("/")
def index():
    return render_template("index.html")


# ─── API Routes ───────────────────────────────────────────────────────────────

@api_bp.route("/health", methods=["GET"])
def health():
    """
    Health check used by Render's uptime monitoring and by the frontend
    to show model load state in the UI header.
    """
    return jsonify({
        "status": "ok",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "models": model_loader.get_status(),
    }), 200


@api_bp.route("/predict", methods=["POST"])
def predict():
    """
    POST body: { "text": "<review text>" }
    Returns sentiment label and per-class confidence scores.
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = data.get("text", "")
    result, status = analysis_controller.analyze_sentiment(text)
    return jsonify(result), status


@api_bp.route("/summarize", methods=["POST"])
def summarize():
    """
    POST body: { "text": "<review text>" }
    Returns an abstractive summary generated by T5-small.
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = data.get("text", "")
    result, status = analysis_controller.analyze_summarization(text)
    return jsonify(result), status


@api_bp.route("/analyze", methods=["POST"])
def analyze():
    """
    POST body: { "text": "<review text>" }
    Runs both sentiment and summarization in one call.
    Useful for the frontend "Analyze" button which wants both at once.
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = data.get("text", "")
    result, status = analysis_controller.analyze_combined(text)
    return jsonify(result), status
